export const SITE = {
  website: "https://lt-20260519-063743875-devosfera-glossary-entity-p-7dadfef0.pages.dev/",
  author: "Devosfera Load Test 06 20260519-063743875 Glossary Entity",
  profile: "https://lt-20260519-063743875-devosfera-glossary-entity-p-7dadfef0.pages.dev/about",
  desc: "Real staging load test batch 20260519-063743875 for Devosfera using Glossary Entity.",
  title: "Devosfera Load Test 06 20260519-063743875 Glossary Entity",
  ogImage: "devosfera-og.svg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: false,
  showGalleriesInIndex: false,
  showBackButton: true,
  heroTerminalPrompt: {
    prefix: "~",
    path: "/ready-to-go",
    suffix: "$",
  },
  backdropEffects: {
    cursorGlow: false,
    grain: true,
  },
  editPost: {
    enabled: false,
    text: "Edit this post",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "en",
  timezone: "UTC",
  introAudio: {
    enabled: false,
    src: "",
    isStream: false,
    label: "",
    duration: 0,
  },
} as const;
